FROM bwits/docker-git-alpine

# Make ssh dir
RUN mkdir -p /root/.ssh/

# Copy over private key, and set permissions
# Warning! Anyone who gets their hands on this image will be able
# to retrieve this private key file from the corresponding image layer
ADD ~/.ssh/id_rsa /root/.ssh/id_rsa

# Clone the conf files into the docker container
# RUN git clone git@github.com:OctavioSI/whatsapp-api.git
